language: go
go:
    - "1.9.x"

os:
    - linux
    - osx

notifications:
    email:
        on_success: never
        on_failure: always

install:
    - export FANTASIM_SDL_VERSION=0.0.1
    - export SDL_PREFIX=/usr/local

    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install dylibbundler; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y rpl; fi

    - ./frontends/tools/sdl_from_source.sh

script:
    - cd frontends/sdl
    - go get -v
    - go build -o fantasim-sdl
    - cd ../../

    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./frontends/tools/package/build_app.sh; fi
    #- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./frontends/tools/package/build_deb.sh; fi

before_deploy:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export FINAL_PACKAGE=fantasim-sdl_osx.zip; fi
    #- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export FINAL_PACKAGE=fantasim-sdl_linux.deb; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export FINAL_PACKAGE=./frontends/tools/package/fantasim-sdl_linux.snap.html; fi

deploy:
    provider: releases
    skip_cleanup: true
    prerelease: true
    file_glob: true
    file: "${FINAL_PACKAGE}"
    on:
        tags: true
        repo: andreas-jonsson/fantasim-pub
    api-key:
        secure: jsjPG5uAuIxNeMV2jKpJXvpkeQykXuRiH88r9TmmSVQIBpMBqSHHtzT73rrePKsZOIJvApgSxq2n28nMFvm+LzkF/q2X2yEA5Db48AnK3K2hZvNkIHYGOrve6812t4ie3D9xW/psX7JdDgGn1qfKH3G9Hx0rjCxKjGYEszQnDrZaW4LsdUWgISr327Ieprge1EsFXRYBXmGXoPoa3cgXa9c+HtNickC8njnaM+G1ZPYN2C0bBOX4QpK9qRgLhRkU4Iq9TCz0MrpV4epK/msYapl8m/3Z4DIthvXN2wZ6B8il0H43m99rWYqci9EkYzjhXteA5TfpZ49SKjWfCfRyL5Lp+Sz2C/Ar7eOs9+XwZN747d857+9JjgxVxC2HWTDyNjOPpfuiTOu/1W1OvCf+vlAH8ft8d7ZhD33XLqs4/7PJw89I0NCDKOJZSt6jGn3dWo4k3lzVklcUmn9eu257gDJcQicCTLUCZU+IsHtIZ4XImdrfJkbWjKprHW0bOBTWA8jinQ6sRB4WGQjxZPkkk21tA7HLXQpcDwZKqbbJCbhVgZjPI8GE9kOxA5ITSat2kmXRmeK2Fy5vC82fjOpLZxOeHKNvULQNPtbqM65mbKxy+dg26MiIFm3naTm6KnmkoK8s+8Y1M5JEjbxdyyrYAw45gyU3NKvknpNkyCR6+Gs=
