version: 0.0.1.{build}

platform: x64

branches:
    only:
        - master

clone_folder: c:\gopath\src\github.com\andreas-jonsson\fantasim-pub

environment:
    GOPATH: c:\gopath

install:
    - appveyor DownloadFile https://storage.googleapis.com/golang/go1.9.3.windows-amd64.msi
    - msiexec /i go1.9.3.windows-amd64.msi /q
    - go version
    - go env

    - set PATH="c:\Program Files (x86)\Inno Setup 5";%GOPATH%\bin;%PATH%

build_script:
    - cd frontends\sdl
    - go get github.com/akavel/rsrc
    - rsrc -ico=icon.ico -arch=amd64
    - go get -v
    - go build -o fantasim-sdl.exe -ldflags="-H windowsgui"

after_build:
    - iscc /Qp /O".\" setup.iss

artifacts:
    - path: frontends/sdl/fantasim-sdl-setup.exe

deploy:
    description: 'Fantasim SDL'
    provider: GitHub
    auth_token:
        secure: kcKpWCf8VCWk8VsjncvYS90wjZoY8LSxTPwNHCQ+mmjls5gt4j9dbsIgTw4gt5le
    artifact: frontends/sdl/fantasim-sdl-setup.exe
    draft: false
    prerelease: true
    on:
        branch: master
#        appveyor_repo_tag: false