version: 0.0.1.{build}

platform: x64

branches:
    only:
        - master

clone_folder: c:\gopath\src\github.com\andreas-jonsson\fantasim-pub

environment:
    GOPATH: c:\gopath
    GO111MODULE: on

install:
    - appveyor DownloadFile https://storage.googleapis.com/golang/go1.12.1.windows-amd64.msi
    - msiexec /i go1.12.1.windows-amd64.msi /q

    - curl -fsS -o dependencies.7z ftp://46.101.144.81/dependencies.7z
    - 7z x dependencies.7z -ofrontends\tools\package

    - curl -fsS -o TDM-GCC-64.7z ftp://46.101.144.81/TDM-GCC-64.7z
    - 7z x TDM-GCC-64.7z -oc:\

    - set PATH="c:\Program Files (x86)\Inno Setup 5";"%GOPATH%\bin";c:\TDM-GCC-64\bin;%PATH%

    - go version
    - go env

build_script:
    - cd frontends\sdl
    - go get -v
    - go get -u github.com/akavel/rsrc
    - go install github.com/akavel/rsrc
    - rsrc -ico=../tools/package/icon.ico -arch=amd64
    - go build -o fantasim-sdl.exe -ldflags=all="-H windowsgui"

after_build:
    - iscc /Qp /O".\" ..\tools\package\setup.iss

artifacts:
    - path: frontends/sdl/fantasim-sdl_*_windows.exe

deploy:
    description: 'Fantasim SDL'
    provider: GitHub
    auth_token:
        secure: kcKpWCf8VCWk8VsjncvYS90wjZoY8LSxTPwNHCQ+mmjls5gt4j9dbsIgTw4gt5le
    artifact: /frontends\/sdl\/fantasim-sdl_(\d+)\.(\d+)\.(\d+)_windows\.exe/
    draft: false
    prerelease: true
    on:
        branch: master
        appveyor_repo_tag: true
