name: fantasim-sdl
version: git
summary: Fantasim-SDL frontend.
description: |
  Fantasim is a fantasy world simulator game similar to Dwarf Fortress and Goblin Camp.

grade: devel
confinement: devmode

parts:
  #go:
  #  source-tag: go1.10
  #  source-depth: 1

  desktop:
    source: frontends/tools/package/snap/
    plugin: dump

  fantasim-sdl:
    stage:
      - bin/fantasim-sdl
    organize:
      bin/sdl: bin/fantasim-sdl
    source: .
    plugin: go
    go-importpath: github.com/andreas-jonsson/fantasim-pub
    go-packages: [github.com/andreas-jonsson/fantasim-pub/frontends/sdl]
    build-packages:
      - pkg-config
      - libsdl2-dev
    stage-packages:
      - libsdl2-2.0-0

apps:
  fantasim-sdl:
    command: bin/fantasim-sdl