name: fantasim
version: git
summary: Fantasim
description: |
  Fantasim is a fantasy world simulator game similar to Dwarf Fortress and Goblin Camp.

grade: devel
confinement: devmode

parts:
  desktop:
    source: frontends/tools/package/fantasim.snap/
    plugin: dump

  fantasim-sdl:
    stage:
      - bin/fantasim
    #organize:
    #  bin/sdl: bin/fantasim
    source: .
    plugin: go
    go-importpath: github.com/andreas-jonsson/fantasim
    #go-packages: [github.com/andreas-jonsson/fantasim]
    #build-packages:
    #  - pkg-config
    #  - libsdl2-dev

apps:
  fantasim:
    command: bin/fantasim
    desktop: usr/share/applications/fantasim.desktop
    #environment:
    #  LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu/pulseaudio