name: fantasim-sdl
version: 0.0.1
summary: Fantasim-SDL frontend.
#icon: usr/local/share/fantasim-sdl/icon256x256.png
architectures: [amd64]
description: |
  Fantasim is a fantasy world simulator game similar to Dwarf Fortress and Goblin Camp.

grade: stable
confinement: strict

parts:
  desktop:
    source: frontends/tools/package/fantasim-sdl.snap/
    plugin: dump

  fantasim-sdl:
    stage:
      - bin/fantasim-sdl
    organize:
      bin/sdl: bin/fantasim-sdl
    source: .
    plugin: go
    go-importpath: github.com/andreas-jonsson/fantasim-pub
    go-packages: [github.com/andreas-jonsson/fantasim-pub/frontends/sdl]
    build-packages: [pkg-config, libsdl2-dev]

  integration:
    plugin: nil
    stage-packages: [xdg-utils, bash]

apps:
  fantasim-sdl:
    command: bin/fantasim-sdl
    desktop: usr/share/applications/fantasim-sdl.desktop
    plugs: [network, x11]
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu/pulseaudio

  xdg-open:
    command: bin/xdg-open
    plugs: [network, network-bind, x11, home, unity7, gsettings]