name: fantasim-sdl
version: git
summary: Fantasim-SDL frontend.
#icon: usr/local/share/fantasim-sdl/icon256x256.png
description: |
  Fantasim is a fantasy world simulator game similar to Dwarf Fortress and Goblin Camp.

grade: devel
confinement: strict

parts:
  desktop:
    source: frontends/tools/package/fantasim-sdl.snap/
    plugin: dump

  fantasim-sdl:
    stage:
      - bin/fantasim-sdl
    organize:
      bin/sdl: bin/fantasim-sdl
    source: .
    plugin: go
    go-importpath: github.com/andreas-jonsson/fantasim-pub
    go-packages: [github.com/andreas-jonsson/fantasim-pub/frontends/sdl]
    plugs:
      - network
      - opengl
      - x11
      - wayland
    build-packages:
      - pkg-config
      - libsdl2-dev
      - mesa-common-dev

apps:
  fantasim-sdl:
    command: bin/fantasim-sdl
    desktop: usr/share/applications/fantasim-sdl.desktop
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu/pulseaudio